operator:
  pullPolicy: IfNotPresent
  replicas: 1
  image: tomekincubly/kafka-schema-operator
  version: master # TODO: switch to release versions?

schemaRegistry:
#  base URL of the "default" schema registry instance. Overridable on resource level
  baseUrl:

# global cleanup policy for the operator, Overridable on resource level
defaultCleanupPolicy: DISABLED
