name: Release version

on:
  push:
    branches: [ "9-add-semantic-versioning" ]

jobs:

  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Perform semantic version
        uses: paulhatch/semantic-version@v5.4.0
        id: semantic_version
        with:
          tag_prefix: "testversiontag"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-rc${increment}"
          user_format_type: "csv"
          bump_each_commit: true
          search_commit_body: true

      - name: Print step outputs
        run: |
          echo "${{join(steps.semantic_version.outputs.*, ',')}}"
          echo "version = ${{steps.semantic_version.outputs.version}}
          echo "version_tag = ${{steps.semantic_version.outputs.version_tag}}
        id: print_outputs

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.semantic_version.outputs.version_tag}}',
              sha: context.sha
            })

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: tomekincubly/kafka-schema-operator

      - name: Build and push Docker
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: '***/kafka-schema-operator:${{ steps.semantic_version.outputs.version }}'
          labels: ${{ steps.meta.outputs.labels }}
